# Name of keyboard
CONFIG_ZMK_KEYBOARD_NAME="Cao_Keeb"

CONFIG_ZMK_BATTERY_REPORT_INTERVAL=180

# Encoder Enable
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Enable Mouse Keys 
CONFIG_ZMK_MOUSE=y

# Display adapter
CONFIG_ZMK_DISPLAY=y

# Display Widgets
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# Eager Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Increase power to bluetooth module
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Fast BLE (7.5ms)
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

# USB Polling rate decrease 
CONFIG_USB_HID_POLL_INTERVAL_MS=1 
#CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# For display screens
CONFIG_I2C=y
CONFIG_SSD1306=y

